### ISSUE TITLE
support for dark theme behind reverse proxy

### ISSUE THREAD

**Issue by NicholasGoh** [NRWLDev/fastapi-swagger-dark#1]
Thanks for this dark theme repo; I love dark themes

However, I have been having issues running this behind reverse proxy.

Below I detail some code on running behind reverse proxy without your dark theme.

```bash
fastapi run --root-path=/api
```

### `nginx.conf`

```
upstream api {
    server api:8000;
}

server {
    listen 80;

    location / {
        return 301 /api/docs;
    }

    location /api/ {
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS, HEAD";
        add_header Access-Control-Allow-Headers "content-type";

        proxy_set_header Cache-Control 'no-cache';
        proxy_set_header Content-Type $http_content_type;
        proxy_set_header X-Accel-Buffering 'no';

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host $host;

        proxy_read_timeout 600;
        proxy_send_timeout 600;

        proxy_buffering off;
        proxy_redirect off;
        proxy_pass http://api/;
    }

    location /api/docs {
        proxy_redirect off;
        proxy_pass http://api/docs;
    }
}
```

### docker compose

```yaml
services:
  nginx:
    image: nginx:1.26.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  api:
    image: <api image>
```

With your dark theme behind reverse proxy, routing of `openapi.json` and `/docs` and `dark_theme.css` does not resolve correctly.

Please correct me if i'm wrong but I think these routing  should be done on your side.
